// Static fixture data for the GoComet V2 demo app. Mirrors the shapes used by
// the V1 demo's Python `gocomet/fixtures.py`, but served over HTTP so the
// renderer can exercise the full DataSourceResolver pipeline (loading state,
// transforms, error handling) instead of inlining `mockData`.

export const SHIPMENT = {
  id: '26030619LA',
  sourcingUnit: 'WEIFANG MINGHENG INTERNATIONAL T...',
  soldTo: 'MAYO HARDWARE PTY LTD',
  shipTo: 'MAYO HARDWARE PTY LTD',
  sellingIncoterm: 'CIF',
  mode: 'Sea',
  carrier: 'Maersk',
  pol: 'Qingdao, China (CNQDG)',
  pod: 'Sydney, Australia (AUSYD)',
  blNumber: 'TAO01560884',
  containers: '2x20ft',
  etd: '11-Mar-2026',
  eta: '15-Mar-2026',
  etaBadge: { label: 'SHORT', variant: 'warning' },
  docStatus: 'Pending',
  docHealth: '3 Available | 5 Pending',
  docHealthBadge: { label: '🚩', variant: 'error' },
  shipmentStatus: 'Dispatched',
}

export const SHIPMENT_DETAILS = {
  shipmentId: '26030619LA',
  shipmentStatus: 'Dispatched',
  bcNumber: '-',
  docStatus: 'Pending',
  blNumber: 'TAO01560884',
  docHealth: '3 Available | 5 Pending',
  carrier: 'MAERSK',
  suInvoiceNumber: '26013B, 26013C, 26013A, 26013D',
  mode: 'Sea',
  uaplInvoiceNumber: '-',
  polCode: 'CNQDG',
  customerPoNumber: '-',
  polName: 'Qingdao, China (CNQDG)',
  sapShipmentReference: '3900612242, 3900612243',
}

export const DRDV_DOCUMENTS = [
  {
    id: 'doc-1',
    name: 'SU Packing List',
    status: 'Extraction Error',
    dueDate: '07-Mar-2026',
    extractionScore: '4 / 5 fields (80%)',
    validationScore: '2 / 5 fields (40%)',
    fields: [
      { name: 'blType', label: 'BL Type', value: null, source: 'Document 1' },
      { name: 'shipper', label: 'Shipper', value: 'UNILEVER NORTH AMERI...', source: 'Document 1' },
      { name: 'quantity', label: 'Quantity', value: 20269, source: 'Document 1' },
      { name: 'consignee', label: 'Consignee', value: 'LUSITANO INC. 1379 SAN...', source: 'Document 1' },
      { name: 'totalCbm', label: 'Total Cbm', value: '40.636', source: 'Document 1' },
      { name: 'netWeight', label: 'Net Weight', value: null, source: 'Document 1' },
      { name: 'grossWeight', label: 'Gross Weight', value: 20269, source: 'Document 1' },
    ],
  },
]

export const MANDATORY_DOCS = [
  { name: 'SU Packing List', status: 'Extraction Error', dueDate: '07-Mar-2026',
    extractScore: '-', validateScore: '-', customerNote: '-', submittedDate: '04-Mar-2026' },
  { name: 'UAPL Invoice', status: 'Ready', dueDate: '07-Mar-2026',
    extractScore: '4 / 5 fields (80%)', validateScore: '2 / 5 fields (40%)',
    customerNote: 'Kindly note that we would like to avoid shipments with MSC, Hapag-Lloyd, and…',
    submittedDate: '04-Mar-2026' },
  { name: 'Draft Bill of Lading', status: 'Validation Pending', dueDate: '07-Mar-2026',
    extractScore: '-', validateScore: '-', customerNote: '-', submittedDate: '04-Mar-2026' },
  { name: 'Booking Confirmation', status: 'Extraction Error', dueDate: '07-Mar-2026',
    extractScore: '4 / 5 fields (80%)', validateScore: '-', customerNote: '-', submittedDate: '04-Mar-2026' },
  { name: 'Draft COO', status: 'Validation Error', dueDate: '07-Mar-2026',
    extractScore: '5 / 5 fields (100%)', validateScore: '-', customerNote: '-', submittedDate: '04-Mar-2026' },
  { name: 'COO', status: 'Overdue', dueDate: '05-Mar-2026',
    extractScore: '-', validateScore: '-', customerNote: 'I need a signed copy of COO.', submittedDate: '-' },
  { name: 'SEAWAY BILL OF LADING', status: 'Pending', dueDate: '09-Mar-2026',
    extractScore: '-', validateScore: '-',
    customerNote: 'Please surrender the original Seaway Bill of Lading.', submittedDate: '-' },
  { name: 'Certificate of Analysis', status: 'Ready', dueDate: '09-Feb-2026',
    extractScore: '9 / 9 fields (100%)', validateScore: '3 / 3 fields (100%)',
    customerNote: '-', submittedDate: '-' },
  { name: 'DG Certificate', status: 'Skipped', dueDate: '10-Mar-2026',
    extractScore: '-', validateScore: '-', customerNote: '-', submittedDate: '-' },
]

export const SHIPMENTS = [
  { shipmentId: '26030619LA', shipmentType: 'LONG', shipmentStatus: 'Dispatched',
    suName: '50488390-CARGO COMPASS OCEAN HUB', soldToName: 'Acme Corporation',
    shipToName: 'Global Logistic Inc', mode: 'Sea', blNumber: 'TAO01560884',
    carrier: 'Maersk', polName: 'Qingdao, China (CNQDG)' },
  { shipmentId: '2603064Z56', shipmentType: '-', shipmentStatus: 'Dispatched',
    suName: '514975-FARMOL S.P.A', soldToName: 'Tech Solutions LLC',
    shipToName: 'Prime Retail Group', mode: 'Sea', blNumber: '-',
    carrier: 'Maersk', polName: 'Naples, Italy' },
  { shipmentId: '260306KZB7', shipmentType: '-', shipmentStatus: 'Dispatched',
    suName: "50156781-'SG Toll'", soldToName: 'Apex Industries',
    shipToName: 'Nexus Distributors', mode: 'Sea', blNumber: '-',
    carrier: 'CMA CGM', polName: 'Singapore' },
  { shipmentId: '2603063N85', shipmentType: 'SHORT', shipmentStatus: 'Dispatched',
    suName: '50285122-Unilever Europe BV HPC-UK-DC Doncaster',
    soldToName: 'Zenith Enterprises', shipToName: 'Horizon Traders',
    mode: 'Sea', blNumber: '-', carrier: 'MSC', polName: 'Doncaster, UK' },
  { shipmentId: '260306JPIS', shipmentType: '-', shipmentStatus: 'In Transit',
    suName: '51089348-ALIMINTER S.A.', soldToName: 'Summit Holdings',
    shipToName: 'Pinnacle Supply', mode: 'Sea', blNumber: '-',
    carrier: 'Hapag-Lloyd', polName: 'Montevideo, Uruguay' },
  { shipmentId: '260305AB12', shipmentType: 'LONG', shipmentStatus: 'Dispatched',
    suName: '40229105-Global Trade Co', soldToName: 'Vertex Industries',
    shipToName: 'Coastal Imports', mode: 'Sea', blNumber: 'MSC90012',
    carrier: 'MSC', polName: 'Shanghai, China' },
  { shipmentId: '260304XY99', shipmentType: '-', shipmentStatus: 'Dispatched',
    suName: '51128922-Nordic Shipping', soldToName: 'Polar Trading',
    shipToName: 'Arctic Goods', mode: 'Sea', blNumber: '-',
    carrier: 'Maersk', polName: 'Rotterdam, NL' },
]
